name: TowersForPGM
version: '${project.version}'
main: org.nicolie.towersforpgm.TowersForPGM
depend: [PGM]
softdepend: [MatchBot]
commands:
  add:
    description: Agregar un jugador al Draft.
    usage: /add <nick>
    permission: towers.captains
  balance:
    description: Balancea los equipos entre los jugadores disponibles.
    usage: /balance <capitan1> <capitan2>
    permission: towers.captains
  cancelMatch:
    description: Cancela una partida y no sube stats a database.
    usage: /cancelMatch
    permission: towers.admin
  captains:
    description: Comienza el Draft con 2 capitanes.
    usage: /captains <nick1> <nick2>
    aliases: [capitanes]
    permission: towers.captains
  elo:
    description: Muestra el ELO de un jugador.
    usage: /elo <jugador>
  forfeit:
    description: Rindete para terminar la partida.
    aliases: [ff]
    usage: /forfeit
  link:
    description: Genera un código para vincular tu cuenta de Discord.
    usage: /link
  pick:
    description: Elegir un jugador para el draft.
    usage: /pick <jugador>
  preparationTime:
    description: Habilita o desactiva el tiempo de preparación.
    usage: /preparationTime <on|off>
    permission: towers.admin
  ranked:
    description: Unete a una partida Ranked.
    usage: /ranked <join|leave|list>
  ready:
    description: Marca como listo a un jugador.
    usage: /ready
  remove:
    description: Eliminar un jugador del Draft.
    usage: /remove <nick>
    aliases: [rem, delete, del]
    permission: towers.captains
  sub:
    description: Sustituir un capitán por otro jugador durante el draft.
    usage: /sub <capitan_actual> <nuevo_capitan>
    permission: towers.captains
  sudo:
    description: Ejecuta un comando como otro jugador.
    usage: /sudo <jugador> <comando>
    permission: towers.developer
  tag:
    description: Tagea a jugadores en discord para jugar rankeds.
    usage: /tag
  towers:
    description: Comando principal de TowersForPGM.
    usage: /towers help
    permission: towers.admin
    aliases: [tt, tower]
  towersForPGM:
    description: Comando principal de TowersForPGM.
    usage: /towersForPGM
    permission: towers.admin
  unlink:
    description: Desvincular una cuenta de Discord usando UUID o Discord ID.
    usage: /unlink <uuid|discordId>
    permission: towers.admin
permissions:
  towers.admin:
    description: Permite administrar y cambiar configuraciones.
    default: op
  towers.captains:
    description: Permite manejar el draft.
    default: op
  towers.developer:
    description: Permite ver mensajes de depuración.
    default: op
  towersstats.use:
    description: Permite ver estadísticas de jugadores.
    default: true