name: TowersForPGM
version: '${project.version}'
main: org.nicolie.towersforpgm.TowersForPGM
depend: [PGM]
softdepend: [MatchBot]
permissions:
  towers.admin:
    description: Permite administrar y cambiar configuraciones.
    default: op
  towers.captains:
    description: Permite manejar el draft.
    default: op
  towers.developer:
    description: Permite ver mensajes de depuración.
    default: op
  towersstats.use:
    description: Permite ver estadísticas de jugadores.
    default: true